### Permission - Command - Description ###
# lightcheck.list - /check list > List of checks now
# lightcheck.check - /check <player> AND access to help commands
# lightcheck.approve - /check approve > Approve checked player
# NONE - /confirm > approve yourself
# lightcheck.rt - /check rt | removetimer > Remove timer
# lightcheck.stop-all - /check stop-all > Stop all checks now
# lightcheck.bypass > protection against a call for verification

config-version: 1.5
# only when the server is turned on
update-notification: true
debug: false

# RUSSIAN or ENGLISH available now
language: ENGLISH

settings:
  title: true
  actionbar: false
  bossbar: true
  message-timer: 10 # every 10 seconds a message will be sent
  timer: 300 # after how many seconds will the player be banned
  # A `logs` folder is being created, which will contain players and actions with them
  logging: true
  # MINIMESSAGE or LEGACY available now
  # Recommended: MINIMESSAGE
  parse_mode: MINIMESSAGE

# block-move may conflict with anti-cheats
abilities:
  teleport-to-inspector:
    enable: true
    after-back: true
  # You can create your own check points and check the players there
  # If the teleportation failed (for example, there is a check in all locations), then it teleports to the inspector
  teleport-to-location:
    enable: false
    after-back: true
    locations:
      - 'world,0:0:0,0:0'
  block-gamemode: true
  block-move: true
  block-drops: true
  block-pickup: true
  block-damage: true
  block-interact: true
  block-chat:
    enable: true
    allowed-commands:
      - 'check'

# Example for disable: approve: []
commands:
  confirm:
    - "kick #player# Self-recognition in cheats"
  approve: # If the PLAYER pleads guilty or the STAFF recognizes the player as a cheater
    - "kick #player# Recognition of the use of cheats"
  disprove: []
  quit:
    - "kick #player# Exit from verification"
  kick:
    - "kick #player# Kicked from this server"