name: LightCheck
main: ru.kainlight.lightcheck.Main
version: ${pluginVersion}
api-version: '1.17'

author: kainlight
description: "To call the player to check the cheats"
website: "https://github.com/kainlighty/LightCheck"

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}
  - net.kyori:adventure-api:${adventureVersion}
  - net.kyori:adventure-text-minimessage:${adventureVersion}
  - net.kyori:adventure-platform-bukkit:${adventureBukkitVersion}

softdepend:
  - PlaceholderAPI

commands:
  lightcheck:
    aliases:
      - lcheck
      - check

permissions:
  lightcheck.list:
    default: op
  lightcheck.check:
    default: op
  lightcheck.bypass:
    default: op
  lightcheck.confirm:
    default: true
  lightcheck.approve:
    default: op
  lightcheck.disprove:
    default: op
  lightcheck.timer.continue:
    default: op
  lightcheck.timer.stop:
    default: op
  lightcheck.timer.*:
    default: op
    children:
      lightcheck.timer.continue: true
      lightcheck.timer.stop: true
  lightcheck.stop-all:
    default: op
  lightcheck.reload:
    default: op
  lightcheck.admin:
    children:
      lightcheck.list: true
      lightcheck.check: true
      lightcheck.bypass: true
      lightcheck.approve: true
      lightcheck.disprove: true
      lightcheck.timer.*: true
      lightcheck.stop-all: true
      lightcheck.reload: true