name: LightCheck
main: ru.kainlight.lightcheck.Main
version: '${project.version}'
api-version: '1.17'

author: kainlight
description: '${pom.description}'
website: '${pom.organization.url}'

libraries:
  - net.kyori:adventure-platform-bukkit:4.3.0
  - net.kyori:adventure-api:4.14.0

softdepend:
  - PlaceholderAPI

commands:
  lightcheck:
    aliases:
      - check
    description: To call the player to check the cheats

permissions:
  lightcheck.list:
    default: op
  lightcheck.check:
    default: op
  lightcheck.bypass:
    default: op
  lightcheck.confirm:
    default: not op
  lightcheck.approve:
    default: not op
  lightcheck.disprove:
    default: op
  lightcheck.timer.continue:
    default: op
  lightcheck.timer.stop:
    default: op
  lightcheck.timer.*:
    default: op
    children:
      lightcheck.timer.continue: true
      lightcheck.timer.stop: true
  lightcheck.stop-all:
    default: op
  lightcheck.reload:
    default: op
  lightcheck.admin:
    children:
      lightcheck.list: true
      lightcheck.check: true
      lightcheck.bypass: true
      lightcheck.approve: true
      lightcheck.disprove: true
      lightcheck.timer.*: true
      lightcheck.stop-all: true
      lightcheck.reload: true
