name: Bug report
description: Create a bug report
labels: ["bug"]
body:
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
    validations:
      required: true
  - type: dropdown
    id: core-select
    attributes:
      label: Select The Core
      options:
        - Spigot
        - Paper
        - Purpur
        - Airplane
        - Pufferfish
        - Mirai
        - Patina
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Be sure to insert StackTrace errors. If there isn't one, describe the problem in as much detail as possible.
    validations:
      required: true