blank_issues_enabled: false
contact_links:
  - name: ✉️ Contact form
    url: https://forms.yandex.ru/cloud/66db55645d2a06399a5151f4/
    about: Or use NIGHTOFTHEKAIN@yandex.com (be sure to specify the subject)