name: 💡 New Feature
description: Create a feature request
labels: ["feature"]
body:
  - type: dropdown
    id: core-select
    attributes:
      label: Select The Core
      options:
        - Spigot
        - Paper
        - Purpur
        - Airplane
        - Pufferfish
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true